server:
  port: 9008
spring:
  datasource:
    username: root
    password: 991224
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/property_manage?tinyInt1isBit=false&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8

mybatis-plus:
  global-config:
    db-config:
      table-prefix: x_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 标准输出形式
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 启用驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/pojo/mapperxml/*.xml
  type-aliases-package:
    - com.domain
    - com.pojo

jwt:
  # Token过期时间 单位：毫秒
  expire: 864500000
  # 密钥 用于加密数据
  secret: oKWI6r6tRbE0MGSF3DbXkWDVBnBMyIQL

file:
  # 是否定期删除上传文件的缓存文件
  clean-cache: true
  # 缓存文件保存时间，单位（天）
  temp-file-save-date: 0

  root: C:\res\${spring.application.name}
  avatar: ${file.root}\avatar\
  tmp: ${file.root}\tmp\
  document: ${file.root}\document\

file-path:
  # 文件URL访问路径前缀
  url: /files
  # 上传文件保存地址
  repository: D:\Temp\files
  # 临时文件保存相对路径
  temp-path: temp