spring:
  profiles:
    active: dev
    include: druid
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: vote-system-demo-vote-pc
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

static-res:
  #  port: 9006
  port: 8999
  suffix: res

#server-ip: 121.196.145.171
server-ip: 82.156.199.7

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: flybear.hziee.app.entity
  global-config:
    db-config:
      table-prefix: x_
      # 全局逻辑删除字段值
      logic-delete-field: deleted

