server:
  port: 80
spring:
  datasource:
    username: root
    password: 991224
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.199.7:3306/vote_system_demo?tinyInt1isBit=false&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    filters: stat,wall,slf4j

mybatis-plus:
  global-config:
    db-config:
      table-prefix: x_

jwt:
  # Token过期时间 单位：毫秒
  expire: 864500000
  # 密钥 用于加密数据
  secret: oKWI6r6tRbE0MGSF3DbXkWDVBnBMyIQL


file:
  # 是否定期删除上传文件的缓存文件
  clean-cache: true
  # 缓存文件保存时间，单位（天）
  temp-file-save-date: 0
file-path:
  # 文件URL访问路径前缀
  url: /files
  # 上传文件保存地址
  repository: D:\Temp\files
  # 临时文件保存相对路径
  temp-path: temp

