spring:
  profiles:
    active: dev
    include: druid
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: flybear.hziee.app.entity
  global-config:
    db-config:
      table-prefix: x_
      # 全局逻辑删除字段值
      logic-delete-field: deleted
